### ISSUE TITLE
Meltano run under Airflow has `MELTANO_FF_STRICT_ENV_VAR_MODE` set unexpectedly

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7291] opened 2023-02-08 21:41 UTC
Related threads on Slack:
- [First user report](https://meltano.slack.com/archives/C01TCRBBJD7/p1674989241095849)
- [Second user report](https://meltano.slack.com/archives/C01TCRBBJD7/p1675878904113949)
- [Question about this in `#internal-engineering`](https://meltano.slack.com/archives/C03GKHWS0HM/p1675884759475469)

In both reported cases the environment variable `MELTANO_FF_STRICT_ENV_VAR_MODE` was being set within Meltano's process, but it's unclear what was setting it. Users report that it was unset within their shell, `.env` file, and `meltano.yml`. In both cases Meltano would only fail when run under Airflow, so it seems likely that Airflow is being given the Meltano settings as env vars somehow, and then setting them as the shell env vars for Meltano when it runs it.

This env var being set exposed an issue (see https://github.com/meltano/meltano/issues/7231) which has since been resolved, but the original problem of the env var being unexpectedly set in the first place has yet to be resolved.

**Comment by tayloramurphy** [comment] 2023-02-09 16:59
@aaronsteers I don't know of any cases that would cause it, but I'm not in the code on a regular basis. Could Airflow itself be a bit of a red herring and it's something else that's causing the problem?

**Comment by qbatten** [comment] 2023-02-21 01:50
Could this be related to my old report here? https://github.com/meltano/meltano/issues/6998
I never "resolved" it, just worked around it by providing empty values for the variables it was complaining about.

**Comment by cjohnhanson** [comment] 2023-03-29 22:55
@tayloramurphy (this is also an update re: https://github.com/meltano/meltano/issues/6998#issuecomment-1472108899) I think this may have been resolved in release 2.15.2 as part of @WillDaSilva's work. Are we aware of any users experiencing this issue since upgrading to 2.15.2+?

I've been unable to replicate this behavior in the latest version, but after spending a long time digging, I have a theory (about 90% confirmed) about why this was happening.

Basically, the strict env var mode feature flag is handled a little bit differently than other settings because we need to "get" it upstream of other settings, since it's a kind of "meta setting" that changes the logic of how we get all other settings. In the initial implementation of it, we weren't checking "truthy-ness" of the value when we got it in this idiosyncratic way. This worked as expected in every case _except_ if it was explicitly set to false via the `MELTANO_FF_STRICT_ENV_VAR_MODE` environment variable. For most use cases outside of airflow, this was acceptable: if it was set in `meltano.yml` or fell back to the default value, it would have the correct boolean type. If it was set to `"true"` within the env var, this was also work as expected, since `bool("true") == True`. _But_ if it was set to `"false"` within the env var, it would still evaluate to `True` since `bool("false") == True`. In our airflow extensions, every setting is passed as an environment variable, so even when falling back to the default setting value, generated dags were calling `meltano run` in an environment where `MELTANO_FF_STRICT_ENV_VAR_MODE` was set to the string `"false"`, which, since we weren't checking truthy-ness in the idiosyncratic way we checked this feature flag, was evaluating to `True`. 

@WillDaSilva CC'ing here for a sanity check of this root cause explanation, or any additional insight you may have. If we haven't had any reports of this behavior on 2.15.2+, I think we can close this issue as resolved and use this comment as the root cause for posterity.

**Comment by WillDaSilva** [comment] 2023-03-30 13:25
> If it was set to `"true"` within the env var, this was also work as expected, since `bool("true") == True`. _But_ if it was set to `"false"` within the env var, it would still evaluate to `True` since `bool("false") == True`. In our airflow extensions, every setting is passed as an environment variable, so even when falling back to the default setting value, generated dags were calling `meltano run` in an environment where `MELTANO_FF_STRICT_ENV_VAR_MODE` was set to the string `"false"`, which, since we weren't checking truthy-ness in the idiosyncratic way we checked this feature flag, was evaluating to `True`.

@cjohnhanson This explanation make sense to me. It explains both why the env var was set (our Airflow extension sets every setting as an env var), and why this was a problem (treating the string `"false"` as the bool `True`). As you say, the latter was fixed in Meltano version 2.15.2. The former has not been changed, and has been surprising to several users. Do we document this behaviour anywhere?

**Closed** 2023-03-30 23:27 UTC
