### ISSUE TITLE
question: Want to get first 10 rows from loader

### ISSUE THREAD

**Issue by AbdullahFiveRiver** [meltano/meltano#8751] opened 2024-09-06 12:40 UTC
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

Hello there,

is there any way to added limit when i load data from extractor, like i have 4 tables but i want use 1 table and get first 10 rows, how i can do this?

plugins:
  extractors:
  - name: tap-mysql
    variant: transferwise
    pip_url: pipelinewise-tap-mysql
    capabilities:
    - catalog
    - state
    - discover
    config:
      user: " "
      password: " "
      host: " "
      port: 3306
      database: " "
    select:
      - test
    tables:
      - name: test
        selected: true  # Ensures the 'test' table is selected
        custom_query: "SELECT * FROM journey1.test LIMIT 2"
      - name: employees
        selected: false 

  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
    
    
    who i get the this thing?

**Comment by edgarrmondragon** [comment] 2024-09-06 20:50
> i have 4 tables but i want use 1 table 

See https://docs.meltano.com/concepts/plugins/#select-extra and https://docs.meltano.com/concepts/plugins/#select-filter-extra.

> and get first 10 rows, how i can do this?

This is currently not supported, see https://github.com/meltano/meltano/issues/8080 for a related request.

**Comment by edgarrmondragon** [comment] 2024-09-06 20:50
Closing as a duplicate of https://github.com/meltano/meltano/issues/8080.

**Closed by edgarrmondragon** 2024-09-06 20:51 UTC
Labels: question, valuestream/Meltano
