### ISSUE TITLE
ci: Performance test failing randomly

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#6683] opened 2022-08-29 20:03 UTC
### Meltano Version

2.5.0

### Python Version

3.10

### Bug scope

Other

### Operating System

Windows

### Description

The test in `tests/meltano/cli/test_cli.py::TestLargeConfigProject::test_list_config_performance ` is failing for combinations of Python and OS:

<img width="1388" alt="Screen Shot 2022-08-29 at 15 00 40" src="https://user-images.githubusercontent.com/16805946/187287970-2b992564-5793-4c67-ab89-b31959f29d53.png">

source: https://github.com/meltano/meltano/runs/8078349477?check_suite_focus=true#step:11:687

**Comment by aaronsteers** [comment] 2022-09-01 22:24
@WillDaSilva, @edgarrmondragon - What's the action here? Should we increase to 20 seconds or remove the test for this combo?

**Comment by aaronsteers** [comment] 2022-09-01 22:26
Marking urgency=high, weight=1.

**Comment by edgarrmondragon** [comment] 2022-09-01 22:42
@aaronsteers Simple solution is to bump the tolerance.

Long term I wonder if this is the best way to run benchmarks. I looked around a bit during research for https://github.com/meltano/meltano/issues/6613, https://github.com/meltano/sdk/pull/887 and https://github.com/meltano/sdk/discussions/906.

It seems like we need something like https://github.com/marketplace/actions/continuous-benchmark that simply alerts us when time exceeds a certain threshold, and lets us keep a history of performance in key components.

**Comment by WillDaSilva** [comment] 2022-09-01 22:47
Would be solved by #6693 

The tricky part is that the performance is massively worse on Windows. Iirc it only needs to be set to 8 seconds for the other platforms.

**Comment by aaronsteers** [comment] 2022-09-02 02:47
Perf testing is hard, admittedly. I don't want to simply retry the failures. The only case I can see where a retry would be the best/right call would be when root cause is an external service failure, and when we can't reasonably mock the external service.


@WillDaSilva and @edgarrmondragon - since this is having a real and present impact on dev cycles and PRa today, I'd lean towards one of these three as a first and immediate remedy:

1. Up the timeout for all tests.
2. Build the timeout into the test matrix so each image in the matrix gets a timeout relative to expected performance.
3. Simply remove the test or mark as expected to fail.
4. Mark as expected to fail conditionally based on underlying OS/image.

Of all these, I lean towards upping the timeout, since it's the simplest and doesn't add complexity into the process.

**Comment by WillDaSilva** [comment] 2022-09-02 02:51
> The only case I can see where a retry would be the best/right call would be when root cause is an external service failure, and when we can't reasonably mock the external service.

That's essentially what this is. The Windows VMs occasionally perform worse, and we can't control that or mock them performing better.

But I agree that resolving the immediate issue takes precedence, and increasing the timeout is the fastest/simplest way to resolve that. I'll open a PR.

**Closed** 2022-09-02 04:18 UTC
Labels: CI/CD, kind/Bug, urgency/High, valuestream/Meltano
