### ISSUE TITLE
Using MELTANO_PROJECT_ROOT in config setting not expanding

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6175] opened 2022-06-13 20:33 UTC
Theres a chance I'm using this wrong as I was previously just passing relative references which were working but it surprised me when this didnt work. If I point tap-csv to a file in my project `data/customer.csv` with a relative reference it works fine but with $MELTANO_PROJECT_ROOT it throws an error where its clear that variable wasnt expanded. Is this expected behavior? I see most references in the docs using `MELTANO_PROJECT_ROOT` in env var mappings, not in actual config settings so that could be it.

```yaml
version: 1
default_environment: dev
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-csv
        config:
          files:
          - entity: customers
            path: $MELTANO_PROJECT_ROOT/data/customers.csv
            keys:
            - id
```

Result `Exception: File path does not exist $MELTANO_PROJECT_ROOT/data/customers.csv`.

**Comment by tayloramurphy** [comment] 2022-06-13 20:43
@pnadolny13 I _think_ that's because we don't expand env vars at that depth. Most likely we would need to update https://docs.meltano.com/guide/configuration#how-to-use to indicate that and then have a follow-on issue to see if we want to expand at all depths.

@aaronsteers @cjohnhanson can you validate this for me (tagging Cody since you worked on this recently!)

**Comment by DouweM** [comment] 2022-06-13 20:48
@tayloramurphy That's right, this is a dupe of https://github.com/meltano/meltano/issues/3171 and https://github.com/meltano/meltano/issues/2436. I had a comment with some technical background in the GitLab original for the latter: https://gitlab.com/meltano/meltano/-/issues/2481#note_468385206.

**Comment by tayloramurphy** [comment] 2022-06-14 15:58
Thanks for those links - I searched but couldn't find those!

Duplicate of #3171

**Comment by tayloramurphy** [comment] 2022-06-14 15:59
Duplicate of https://github.com/meltano/meltano/issues/3171

**Closed by tayloramurphy** 2022-06-14 15:59 UTC
Labels: kind::bug
