### ISSUE TITLE
bug: using `config` to list config.json fails for mappers

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#7849] opened 2023-06-26 19:47 UTC
Standalone mappers dont work with the config command. I wanted to see what config was being passed when I run a sync but it looks like it always returns and empty dict or fails if I use the mapping name instead of the mapper plugin name itself. This configuration does in fact work the way I want it to, so I think `meltano run` logic is properly creating and passing the config.json that I want.

![Screen Shot 2023-06-26 at 3 44 44 PM](https://github.com/meltano/meltano/assets/27376735/d345b103-c3af-49ec-9561-5184e3461527)

**Comment by tayloramurphy** [comment] 2023-06-26 22:02
Duplicate of https://github.com/meltano/meltano/issues/3195

**Closed by tayloramurphy** 2023-06-26 22:02 UTC
