### ISSUE TITLE
feature: Fetch First 10 Rows

### ISSUE THREAD

**Issue by AbdullahFiveRiver** [meltano/meltano#8759] opened 2024-09-10 13:15 UTC
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

Hello,

Im usning meltano CLI, im facing one issue since many days, the issue is i want to fetch just 10 rows of table but they return me all the rows how i can over come from this? im try filers, select is working but this thing is not working have any solution of this?

Thanks

**Comment by edgarrmondragon** [comment] 2024-09-11 01:41
Hi @AbdullahFiveRiver!

I'm closing this as a duplicate of https://github.com/meltano/meltano/issues/8080. Do comment here or in the other issue if you disagree. Please leave a 👍 there if that's the use case you're looking for.

**Closed by edgarrmondragon** 2024-09-11 01:41 UTC
Labels: kind/Feature, valuestream/Meltano
