### ISSUE TITLE
feature: `meltano config set` default should be --interactive

### ISSUE THREAD

**Issue by visch** [meltano/meltano#7674] opened 2023-05-16 18:00 UTC
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

When setting configurations I end up typing out `meltano config tap-monday set --interactive` a lot (great feature!)

It would be nicer if instead of `meltano config tap-monday set` returning
```
visch@DESKTOP-9BDPA9T:~/git/tap-monday$ meltano config tap-monday set
2023-05-16T17:58:53.673276Z [info     ] The default environment 'test' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.
/home/visch/.local/pipx/venvs/meltano/lib/python3.8/site-packages/meltano/cli/interactive/config.py:390: RuntimeWarning: Unknown setting ''
  value, metadata = settings.set_with_metadata(
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

not enough values to unpack (expected at least 1, got 0)
```

It would run --interactive by default!

**Comment by edgarrmondragon** [comment] 2023-05-16 18:22
Related:

* https://github.com/meltano/meltano/issues/6861#issuecomment-1545903562

**Comment by edgarrmondragon** [comment] 2023-05-16 18:23
@visch this is probably a duplicate of #6861

**Comment by tayloramurphy** [comment] 2023-05-16 19:52
Duplicate of https://github.com/meltano/meltano/issues/6861

**Closed by tayloramurphy** 2023-05-16 19:52 UTC
Labels: kind/Feature, valuestream/Meltano
