### ISSUE TITLE
Can't use default_replication_method INCREMENTAL with tap-postgres

### ISSUE THREAD

**Issue by willjohnson** [meltano/meltano#6282] opened 2022-06-24 15:34 UTC
With meltano 2.0.3, if I have default_replication_method set as INCREMENTAL with tap-postgres then I get an error.

`meltano config tap-postgres test`

```
2022-06-24T15:26:15.923809Z [info     ] Environment 'dev' is active

Plugin configuration is invalid

AttributeError: 'NoneType' object has no attribute 'get'
```

Changing default_replication_method to either FULL_TABLE or LOG_BASED gets past the error and returns "Plugin configuration is valid"

meltano.yml
```
version: 1
default_environment: dev
project_id: fc0cd1d8-5717-4675-9102-c660d25017d5
plugins:
  extractors:
  - name: tap-postgres
    variant: transferwise
    pip_url: pipelinewise-tap-postgres
  loaders:
  - name: target-postgres
    variant: transferwise
    pip_url: pipelinewise-target-postgres
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-postgres
        config:
          user: meltano_test_user
          dbname: meltano_test
          filter_schema: src_sample_store
          start_date: '2022-06-24T00:00:00Z'
          default_replication_method: INCREMENTAL 
          metadata:
            meltano_test-src_sample_store:
              replication-key: updated_at
              replication-method: INCREMENTAL
      loaders:
      - name: target-postgres
        config:
          user: meltano_test_user
          dbname: meltano_test_dw
          schema_mapping:
            src_sample_store: dest_sample_store
- name: staging
- name: prod
```

**Comment by willjohnson** [comment] 2022-06-24 15:47
```
time=2022-06-24 10:46:42 name=tap_postgres level=INFO message=Selected streams: ['src_sample_store-widgets']
time=2022-06-24 10:46:42 name=tap_postgres level=INFO message=No streams marked as currently_syncing in state file
time=2022-06-24 10:46:42 name=tap_postgres level=INFO message=Beginning sync of stream(src_sample_store-widgets) with sync method(incremental)
time=2022-06-24 10:46:42 name=tap_postgres level=INFO message=Stream src_sample_store-widgets is using incremental replication with replication key None
{"type": "SCHEMA", "stream": "src_sample_store-widgets", "schema": {"type": "object", "properties": {"id": {"type": ["integer"], "minimum": -2147483648, "maximum": 2147483647}, "name": {"type": ["null", "string"]}, "widget_type": {"type": ["null", "string"]}, "created_at": {"type": ["null", "string"], "format": "date-time"}, "updated_at": {"type": ["null", "string"], "format": "date-time"}}, "definitions": {"sdc_recursive_integer_array": {"type": ["null", "integer", "array"], "items": {"$ref": "#/definitions/sdc_recursive_integer_array"}}, "sdc_recursive_number_array": {"type": ["null", "number", "array"], "items": {"$ref": "#/definitions/sdc_recursive_number_array"}}, "sdc_recursive_string_array": {"type": ["null", "string", "array"], "items": {"$ref": "#/definitions/sdc_recursive_string_array"}}, "sdc_recursive_boolean_array": {"type": ["null", "boolean", "array"], "items": {"$ref": "#/definitions/sdc_recursive_boolean_array"}}, "sdc_recursive_timestamp_array": {"type": ["null", "string", "array"], "format": "date-time", "items": {"$ref": "#/definitions/sdc_recursive_timestamp_array"}}, "sdc_recursive_object_array": {"type": ["null", "object", "array"], "items": {"$ref": "#/definitions/sdc_recursive_object_array"}}}}, "key_properties": ["id"], "bookmark_properties": [null]}
{"type": "STATE", "value": {"bookmarks": {"src_sample_store-widgets": {"last_replication_method": "INCREMENTAL", "replication_key": null, "version": 1656085602824}}, "currently_syncing": "src_sample_store-widgets"}}
{"type": "ACTIVATE_VERSION", "stream": "src_sample_store-widgets", "version": 1656085602824}
time=2022-06-24 10:46:42 name=tap_postgres level=CRITICAL message='NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/mnt/c/Users/wjohnson/workspace/meltano-projects/meltano_debug/.meltano/extractors/tap-postgres/venv/bin/tap-postgres", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/wjohnson/workspace/meltano-projects/meltano_debug/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/tap_postgres/__init__.py", line 435, in main
    raise exc
  File "/mnt/c/Users/wjohnson/workspace/meltano-projects/meltano_debug/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/tap_postgres/__init__.py", line 432, in main
    main_impl()
  File "/mnt/c/Users/wjohnson/workspace/meltano-projects/meltano_debug/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/tap_postgres/__init__.py", line 421, in main_impl
    do_sync(conn_config, args.catalog.to_dict() if args.catalog else args.properties,
  File "/mnt/c/Users/wjohnson/workspace/meltano-projects/meltano_debug/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/tap_postgres/__init__.py", line 312, in do_sync
    state = sync_traditional_stream(conn_config,
  File "/mnt/c/Users/wjohnson/workspace/meltano-projects/meltano_debug/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/tap_postgres/__init__.py", line 175, in sync_traditional_stream
    state = do_sync_incremental(conn_config, stream, state, desired_columns, md_map)
  File "/mnt/c/Users/wjohnson/workspace/meltano-projects/meltano_debug/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/tap_postgres/__init__.py", line 86, in do_sync_incremental
    state = incremental.sync_table(conn_config, stream, state, desired_columns, md_map)
  File "/mnt/c/Users/wjohnson/workspace/meltano-projects/meltano_debug/.meltano/extractors/tap-postgres/venv/lib/python3.8/site-packages/tap_postgres/sync_strategies/incremental.py", line 61, in sync_table
    replication_key_sql_datatype = md_map.get(('properties', replication_key)).get('sql-datatype')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by tayloramurphy** [comment] 2022-06-24 15:54
@willjohnson looking at https://github.com/meltano/hub/blob/main/_data/meltano/extractors/tap-postgres/transferwise.yml and https://github.com/transferwise/pipelinewise-tap-postgres#run-the-tap-in-sync-mode it seems that we may have the wrong `capabilities` listed for that variant of tap-postgres on MeltanoHub. It has `catalog` when `properties`.

https://hub.meltano.com/singer/docs#tap-specific has some info on the distinction between the `catalog` and `properties` capability. I think if you add 

```yaml
capabilities:
- properties
- discover
- state
```

to your plugin definition that may solve it. You may need to re-lock the definition which you can do manually or if you're on 2.1 (see the [release notes](https://github.com/meltano/meltano/releases/tag/v2.1.0))

**Comment by DouweM** [comment] 2022-06-24 20:27
We found out in [Slack](https://meltano.slack.com/archives/C01TCRBBJD7/p1656102279785449?thread_ts=1656089836.794389&cid=C01TCRBBJD7) that this is a duplicate of https://github.com/meltano/meltano/issues/3322. Moving the `metadata` out of `environments` and to the top-level `tap-postgres` fixed the issue!

**Comment by tayloramurphy** [comment] 2022-06-24 21:53
Duplicate of https://github.com/meltano/meltano/issues/3322

**Closed by tayloramurphy** 2022-06-24 21:53 UTC
Labels: User Support, kind/Bug, valuestream/Meltano
