### ISSUE TITLE
bug: db migration no such revision 2.3.0 -> 2.9.0

### ISSUE THREAD

**Issue by visch** [meltano/meltano#6989] opened 2022-11-15 17:53 UTC
### Meltano Version

2.3.0 -> 2.9.0

### Python Version

3.8

### Bug scope

API

### Operating System

Windows

### Description

2.3.0 -> 2.9.0 is causing me errors. I don't mind so much as I can delete the DB file easily in my case but it slowed me down and I'm guessing for others it's a bigger deal. 

```
2022-11-15T17:22:39.340213Z [error    ] No such revision or branch '6828cc5b1a4f' 
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ C:\Python39\lib\site-packages\meltano\core\migration_service.py:89 in       │
│ upgrade                                                                     │
│                                                                             │
│    86 │   │   try:  # noqa: WPS229                                          │
│    87 │   │   │   # try to find the locked version                          │
│    88 │   │   │   head = LOCK_PATH.open().read().strip()                    │
│ >  89 │   │   │   self.ensure_migration_needed(script, context, head)       │
│    90 │   │   │                                                             │
│    91 │   │   │   if not silent:                                            │
│    92 │   │   │   │   click.secho(f"Upgrading database to {head}")          │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │                cfg = <alembic.config.Config object at                   │ │
│ │                      0x000002B[207](https://gitlab.com/autoidm/***/-/jobs/3327273153#L207)988340>                                │ │
│ │               conn = <sqlalchemy.engine.base.Connection object at       │ │
│ │                      0x000002B207BEBBE0>                                │ │
│ │            context = <alembic.runtime.migration.MigrationContext object │ │
│ │                      at 0x000002B[209](https://gitlab.com/autoidm/***/-/jobs/3327273153#L209)880670>                             │ │
│ │                err = ResolutionError("No such revision or branch        │ │
│ │                      '6828cc5b1a4f'")                                   │ │
│ │               head = '5b43800443d1'                                     │ │
│ │   migration_logger = <_FixedFindCallerLogger alembic.runtime.migration  │ │
│ │                      (ERROR)>                                           │ │
│ │ original_log_level = 20                                                 │ │
│ │             script = <alembic.script.base.ScriptDirectory object at     │ │
│ │                      0x000002B209880B80>                                │ │
│ │               self = <meltano.core.migration_service.MigrationService   │ │
│ │                      object at 0x000002B207BEB8B0>                      │ │
│ │             silent = True                                               │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ C:\Python39\lib\site-packages\meltano\core\migration_service.py:55 in       │
│ ensure_migration_needed                                                     │
│                                                                             │
│    52 │   │   """                                                           │
│    53 │   │   current_head = context.get_current_revision()                 │
│    54 │   │                                                                 │
│ >  55 │   │   for rev in script.iterate_revisions(current_head, "base"):    │
│    56 │   │   │   if rev.revision == target_revision:                       │
│    57 │   │   │   │   raise MigrationUneededException                       │
│    58                                                                       │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │         context = <alembic.runtime.migration.MigrationContext object at │ │
│ │                   0x000002B209880670>                                   │ │
│ │    current_head = '6828cc5b1a4f'                                        │ │
│ │          script = <alembic.script.base.ScriptDirectory object at        │ │
│ │                   0x000002B209880B80>                                   │ │
│ │            self = <meltano.core.migration_service.MigrationService      │ │
│ │                   object at 0x000002B207BEB8B0>                         │ │
│ │ target_revision = '5b43800443d1'                                        │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ C:\Python39\lib\site-packages\alembic\script\revision.py:799 in             │
│ iterate_revisions                                                           │
│                                                                             │
│    796 │   │   else:                                                        │
│    797 │   │   │   fn = self._collect_upgrade_revisions                     │
│    798 │   │                                                                │
│ >  799 │   │   revisions, heads = fn(                                       │
│    800 │   │   │   upper,                                                   │
│    801 │   │   │   lower,                                                   │
│    802 │   │   │   inclusive=inclusive,                                     │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │ assert_relative_length = True                                           │ │
│ │                     fn = <bound method                                  │ │
│ │                          RevisionMap._collect_upgrade_revisions of      │ │
│ │                          <alembic.script.revision.RevisionMap object at │ │
│ │                          0x000002B209880A00>>                           │ │
│ │          implicit_base = False                                          │ │
│ │              inclusive = False                                          │ │
│ │                  lower = 'base'                                         │ │
│ │   select_for_downgrade = False                                          │ │
│ │                   self = <alembic.script.revision.RevisionMap object at │ │
│ │                          0x000002B209880A00>                            │ │
│ │                  upper = '6828cc5b1a4f'                                 │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ C:\Python39\lib\site-packages\alembic\script\revision.py:1426 in            │
│ _collect_upgrade_revisions                                                  │
│                                                                             │
│   1423 │   │   """                                                          │
│   1424 │   │   targets: Collection[Revision] = [                            │
│   1425 │   │   │   is_revision(rev)                                         │
│ > 1426 │   │   │   for rev in self._parse_upgrade_target(                   │
│   1427 │   │   │   │   current_revisions=lower,                             │
│   1428 │   │   │   │   target=upper,                                        │
│   1429 │   │   │   │   assert_relative_length=assert_relative_length,       │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │ assert_relative_length = True                                           │ │
│ │          implicit_base = False                                          │ │
│ │              inclusive = False                                          │ │
│ │                  lower = 'base'                                         │ │
│ │                   self = <alembic.script.revision.RevisionMap object at │ │
│ │                          0x000002B209880A00>                            │ │
│ │                  upper = '6828cc5b1a4f'                                 │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ C:\Python39\lib\site-packages\alembic\script\revision.py:1218 in            │
│ _parse_upgrade_target                                                       │
│                                                                             │
│   1[215](https://gitlab.com/autoidm/***/-/jobs/3327273153#L215) │   │                                                                │
│   1[216](https://gitlab.com/autoidm/***/-/jobs/3327273153#L216) │   │   if not match:                                                │
│   1[217](https://gitlab.com/autoidm/***/-/jobs/3327273153#L217) │   │   │   # No relative destination, target is absolute.           │
│ > 1[218](https://gitlab.com/autoidm/***/-/jobs/3327273153#L218) │   │   │   return self.get_revisions(target)                        │
│   1219 │   │                                                                │
│   1220 │   │   current_revisions_tup: Union[str, Collection[Optional[str]], │
│   1221 │   │   current_revisions_tup = util.to_tuple(current_revisions)     │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │ assert_relative_length = True                                           │ │
│ │      current_revisions = 'base'                                         │ │
│ │                  match = None                                           │ │
│ │                   self = <alembic.script.revision.RevisionMap object at │ │
│ │                          0x000002B209880A00>                            │ │
│ │                 target = '6828cc5b1a4f'                                 │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ C:\Python39\lib\site-packages\alembic\script\revision.py:552 in             │
│ get_revisions                                                               │
│                                                                             │
│    549 │   │   │   │   except ValueError:                                   │
│    550 │   │   │   │   │   # couldn't resolve as integer                    │
│    551 │   │   │   │   │   pass                                             │
│ >  552 │   │   │   return tuple(                                            │
│    553 │   │   │   │   self._revision_for_ident(rev_id, branch_label)       │
│    554 │   │   │   │   for rev_id in resolved_id                            │
│    555 │   │   │   )                                                        │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │ branch_label = None                                                     │ │
│ │          id_ = '6828cc5b1a4f'                                           │ │
│ │  resolved_id = ('6828cc5b1a4f',)                                        │ │
│ │         self = <alembic.script.revision.RevisionMap object at           │ │
│ │                0x000002B209880A00>                                      │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ C:\Python39\lib\site-packages\alembic\script\revision.py:553 in <genexpr>   │
│                                                                             │
│    550 │   │   │   │   │   # couldn't resolve as integer                    │
│    551 │   │   │   │   │   pass                                             │
│    552 │   │   │   return tuple(                                            │
│ >  553 │   │   │   │   self._revision_for_ident(rev_id, branch_label)       │
│    554 │   │   │   │   for rev_id in resolved_id                            │
│    555 │   │   │   )                                                        │
│    556                                                                      │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │           .0 = <tuple_iterator object at 0x000002B2098809A0>            │ │
│ │ branch_label = None                                                     │ │
│ │       rev_id = '6828cc5b1a4f'                                           │ │
│ │         self = <alembic.script.revision.RevisionMap object at           │ │
│ │                0x000002B209880A00>                                      │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
│                                                                             │
│ C:\Python39\lib\site-packages\alembic\script\revision.py:624 in             │
│ _revision_for_ident                                                         │
│                                                                             │
│    621 │   │   │   if branch_rev:                                           │
│    622 │   │   │   │   revs = self.filter_for_lineage(revs, check_branch)   │
│    623 │   │   │   if not revs:                                             │
│ >  624 │   │   │   │   raise ResolutionError(                               │
│    625 │   │   │   │   │   "No such revision or branch '%s'%s"              │
│    626 │   │   │   │   │   % (                                              │
│    627 │   │   │   │   │   │   resolved_id,                                 │
│                                                                             │
│ ┌──────────────────────────────── locals ─────────────────────────────────┐ │
│ │   branch_rev = None                                                     │ │
│ │ check_branch = None                                                     │ │
│ │  resolved_id = '6828cc5b1a4f'                                           │ │
│ │     revision = False                                                    │ │
│ │         revs = []                                                       │ │
│ │         self = <alembic.script.revision.RevisionMap object at           │ │
│ │                0x000002B209880A00>                                      │ │
│ └─────────────────────────────────────────────────────────────────────────┘ │
└─────────────────────────────────────────────────────────────────────────────┘
ResolutionError: No such revision or branch '6828cc5b1a4f'
Cannot upgrade the system database. It might be corrupted or was created before database migrations where introduced (v0.34.0)
17:22:43  Running with dbt=1.0.4
```

**Comment by tayloramurphy** [comment] 2022-11-15 18:34
@aaronsteers I'm adding this to the Engineering board. FYI @meltano/engineering since this is a DB migration issue.

**Comment by tayloramurphy** [comment] 2022-11-29 15:06
We had a user report this as well. Migrating from 2.5.0 to 2.10.0.

**Comment by tayloramurphy** [comment] 2022-11-29 15:09
@cjohnhanson since you're already assigned to https://github.com/meltano/meltano/issues/6871 I'm going to assign you to this one as well.

**Comment by aaronsteers** [comment] 2022-12-14 05:36
High urgency, weight of `8`. I'm bumping up to Rank `5`.

Engineers should be free to pick this up when capacity becomes available.

Please ping in this thread if any clarification / disambiguation is needed.

**Comment by cjohnhanson** [comment] 2022-12-21 00:10
@visch Have you been able to replicate this? If possible, could you share what you remember of your version history and upgrade path? Particularly: what Meltano version was the DB first created with, what prior upgrades had you run before attempting to do this upgrade--any details you have would be helpful in my trying to replicate this and troubleshoot.

@tayloramurphy could you link to the user report you mentioned?

I've tried replicating this issue as follows and haven't been able to throw the same error:
- In a 3.8.13 virtual env, `pip3 install meltano==v2.3.0`
- init a project
- Run some pipelines to populate the db
- `pip3 install --force-reinstall meltano==v2.9.0`
- `meltano upgrade database`

The migration runs successfully for me [and that revision definitely exists](https://github.com/meltano/meltano/blob/main/src/meltano/migrations/versions/6828cc5b1a4f_create_dedicated_state_table.py). Struggling to find a path forward on this if it's only occurring in some very specific upgrade path/version history.

**Comment by visch** [comment] 2022-12-21 02:56
> @visch Have you been able to replicate this? If possible, could you share what you remember of your version history and upgrade path? Particularly: what Meltano version was the DB first created with, what prior upgrades had you run before attempting to do this upgrade--any details you have would be helpful in my trying to replicate this and troubleshoot.
> 
> @tayloramurphy could you link to the user report you mentioned?
> 
> I've tried replicating this issue as follows and haven't been able to throw the same error:
> 
> * In a 3.8.13 virtual env, `pip3 install meltano==v2.3.0`
> * init a project
> * Run some pipelines to populate the db
> * `pip3 install --force-reinstall meltano==v2.9.0`
> * `meltano upgrade database`
> 
> The migration runs successfully for me [and that revision definitely exists](https://github.com/meltano/meltano/blob/main/src/meltano/migrations/versions/6828cc5b1a4f_create_dedicated_state_table.py). Struggling to find a path forward on this if it's only occurring in some very specific upgrade path/version history.

My theory that upgrading from 2.3.0 -> 2.9.0 was wrong. I dove pretty deep here as I thought I had these steps down and I think I see my past logic error. Sorry to waste your time @cjohnhanson 

I thought I was running on 2.9.0, and I wasn't (convoluted CI process I was building at the time). I was running a `meltano install` with version `2.9.0` and I believe that upgraded the database, then I ran with meltano `2.3.0` and that's what led to this error (Note the non venv in the logs). I do have the db file if that's helpful (sent to Cody in slack). But I think this one is actually https://github.com/meltano/meltano/issues/6870 

To replicate @cjohnhanson do the same steps you did https://github.com/meltano/meltano/issues/6989#issuecomment-1360534795 and then go back to meltano 2.3.0 and run the job. 

We can probably close this as the title is not correct, but maybe we could write up this error?

**Comment by cjohnhanson** [comment] 2022-12-21 16:09
@visch no worries, I'll link to this in #6989 and then close this.

@tayloramurphy -- is it possible that the user report you referenced could be a similar case where they inadvertently upgraded their DB to a newer version and then were unable to downgrade?

**Comment by tayloramurphy** [comment] 2022-12-21 17:48
@cjohnhanson it was in a DM. context i have:

```
did meltano have like a db migration or something recently? seeing some really cryptic errors when we just upgraded to 2.10.0

we upgraded and then all our pipeline started taking like 30min to even startup

then we reverted the upgrade and now were seeing:

No such revision or branch '6828cc5b1a4f'
```

**Comment by cjohnhanson** [comment] 2022-12-21 17:51
@tayloramurphy yeah that definitely seems like #6989 would be the culprit there. 

Closing this issue as a dupe of that one.

**Closed by cjohnhanson** 2022-12-21 17:51 UTC
Labels: kind/Bug, valuestream/Meltano
