### ISSUE TITLE
bug: pre-commit fails in CI on files that we're not updated

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#7386] opened 2023-03-16 15:17 UTC
PR https://github.com/meltano/meltano/pull/7385 updating only docs but fails CI tests because of these seemingly unrelated precommit tests https://results.pre-commit.ci/run/github/378997214/1678975479.B-Kg4nq3SzupwxvVY7Lkxw.

**Comment by WillDaSilva** [comment] 2023-03-16 15:54
I'm not sure what the cause of this is. This has been fixed in the `cloud` branch. I'll cherry-pick the fix into `main` using a PR.

**Closed** 2023-03-16 20:32 UTC
