### ISSUE TITLE
bug: Meltano is slow to start

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6597] opened 2022-08-09 16:15 UTC
There appears to be a bug causing some users to have a slow startup, up to 45 seconds in the provided logs

Pre 2.x:

```
(.venv) ➜  dutchie-dagster-meltano git:(NoJIRA-upgrade-dagster-meltano) ✗ meltano --version
meltano, version 1.100.0
(.venv) ➜  dutchie-dagster-meltano git:(NoJIRA-upgrade-dagster-meltano) ✗ time meltano --log-level debug config tap-exchange-rates-api list
2022-08-08T22:33:35.566057Z [debug    ] Creating engine <meltano.core.project.Project object at 0x10e248970>@sqlite:////Users/dwall/repos/dagster/dutchie-dagster-meltano/.meltano/meltano.db
2022-08-08T22:33:35.815951Z [debug    ] Using selector: KqueueSelector
2022-08-08T22:33:35.848522Z [debug    ] Created configuration at /Users/dwall/repos/dagster/dutchie-dagster-meltano/.meltano/run/tap-exchange-rates-api/tap.e8b67d7e-f096-4197-b805-e51bcf5971a8.config.json
2022-08-08T22:33:35.848773Z [debug    ] Could not find tap.properties.json in /Users/dwall/repos/dagster/dutchie-dagster-meltano/.meltano/extractors/tap-exchange-rates-api/tap.properties.json, skipping.
2022-08-08T22:33:35.848938Z [debug    ] Could not find tap.properties.cache_key in /Users/dwall/repos/dagster/dutchie-dagster-meltano/.meltano/extractors/tap-exchange-rates-api/tap.properties.cache_key, skipping.
2022-08-08T22:33:35.849094Z [debug    ] Could not find state.json in /Users/dwall/repos/dagster/dutchie-dagster-meltano/.meltano/extractors/tap-exchange-rates-api/state.json, skipping.

Custom, possibly unsupported by the plugin:
base [env: TAP_EXCHANGE_RATES_API_BASE] current value: 'USD' (from `meltano.yml`)
start_date [env: TAP_EXCHANGE_RATES_API_START_DATE] current value: '2018-01-01' (from `meltano.yml`)
symbols [env: TAP_EXCHANGE_RATES_API_SYMBOLS] current value: ['CAD', 'MXN', 'AUD', 'EUR', 'USD'] (from `meltano.yml`)
meltano --log-level debug config tap-exchange-rates-api list  1.64s user 0.20s system 99% cpu 1.849 total
```

Vs in 2.4.0:

```
(.venv) ➜  dutchie-dagster-meltano git:(NoJIRA-upgrade-dagster-meltano) ✗ meltano --version
meltano, version 2.4.0
(.venv) ➜  dutchie-dagster-meltano git:(NoJIRA-upgrade-dagster-meltano) ✗ date && time meltano --log-level debug config tap-exchange-rates-api list && date
Mon Aug  8 15:46:01 PDT 2022
2022-08-08T22:46:45.104438Z [debug    ] Creating engine <meltano.core.project.Project object at 0x10c521760>@sqlite:////Users/dwall/repos/dagster/dutchie-dagster-meltano/.meltano/meltano.db
2022-08-08T22:46:45.406143Z [debug    ] loaded lazy attr 'SafeConfigParser': <class 'configparser.ConfigParser'>
2022-08-08T22:46:45.406251Z [debug    ] loaded lazy attr 'NativeStringIO': <class '_io.StringIO'>
2022-08-08T22:46:45.406330Z [debug    ] loaded lazy attr 'BytesIO': <class '_io.BytesIO'>

Custom, possibly unsupported by the plugin:
base [env: TAP_EXCHANGE_RATES_API_BASE] current value: 'USD' (from `meltano.yml`)
start_date [env: TAP_EXCHANGE_RATES_API_START_DATE] current value: '2018-01-01' (from `meltano.yml`)
symbols [env: TAP_EXCHANGE_RATES_API_SYMBOLS] current value: ['CAD', 'MXN', 'AUD', 'EUR', 'USD'] (from `meltano.yml`)
meltano --log-level debug config tap-exchange-rates-api list  76.80s user 0.50s system 97% cpu 1:18.94 total
Mon Aug  8 15:47:20 PDT 2022
```

More detail in Slack thread: https://meltano.slack.com/archives/C01TCRBBJD7/p1659998566724249?thread_ts=1659985256.778899&cid=C01TCRBBJD7

**Comment by aaronsteers** [comment] 2022-08-11 19:03
@dwallace0723 - Apologies for the delay. We've not yet been able to repro this on our side. We may need to ask for additional tests and/or a zoom call might be helpful to walkthrough with you. @WillDaSilva is digging deeper and may reach out for additional info if that's okay.

**Comment by dwallace0723** [comment] 2022-08-11 19:49
@aaronsteers no problem. happy to assist in any way I can.

**Comment by dwallace0723** [comment] 2022-08-15 20:05
cc @dehume

**Comment by WillDaSilva** [comment] 2022-08-17 16:09
Thanks to @dehume, I've been able to review some fairly detailed profiling information taken from the slow run. I've attached a call graph below.

Almost the entire execution is spent running the standard library function `copy.deepcopy`. The two sites which are making the slow calls to `deepcopy` are:

- https://github.com/meltano/meltano/blob/v2.4.0/src/meltano/core/project_files.py#L47
- https://github.com/meltano/meltano/blob/v2.4.0/src/meltano/core/plugin/project_plugin.py#L178

Much of the time spent in the `deepcopy` calls is spent in [`ruamel.yaml.CommentedMap.__deepcopy__`](https://sourceforge.net/p/ruamel-yaml/code/ci/0.17.21/tree/comments.py#l1069), which in turn calls `deepcopy` recursively approximately 111,400,000 times.

I am able to reproduce the performance issue locally by using a large `meltano.yml` file, most of which is a list of arbitrary numbers. As part of addressing this performance issue, a performance test should be added that ensures that having a large `meltano.yml` file (e.g. 1000 lines long) does not take significantly longer to process than a short `meltano.yml` file.

![Image](https://user-images.githubusercontent.com/11428666/185144029-762bdc03-4aad-44a5-8882-4330b8fb361d.png)

Possible approaches to resolving this:
- Use a custom subclass of `ruamel.yaml.CommentedMap` that (somehow) avoids the problem.
- Sufficiently avoid/reduce calls to `copy.deepcopy`.

**Comment by edgarrmondragon** [comment] 2022-08-17 19:19
@WillDaSilva thanks for digging! I think it's fairly safe to use `copy.copy` instead in

https://github.com/meltano/meltano/blob/3bf8d54b69b2758fb2f3fa7fd6bd0abde156ff3c/src/meltano/core/project_files.py#L47

That might improve performance somewhat.

**Comment by aaronsteers** [comment] 2022-08-17 19:26
> @WillDaSilva thanks for digging! I think it's fairly safe to use `copy.copy` instead in
> 
> https://github.com/meltano/meltano/blob/3bf8d54b69b2758fb2f3fa7fd6bd0abde156ff3c/src/meltano/core/project_files.py#L47
> 
> That might improve performance somewhat.

This makes sense to me too - especially since that deepcopy reference is recursively called.

**Comment by WillDaSilva** [comment] 2022-08-17 20:12
@edgarrmondragon Thank you for the suggestion. That helps, and is one of the improvements I had tried, but is insufficient on its own. I'm thinking we can probably solve this by caching a hash of `meltano.yml` in-memory along with data parsed from it. Then on subsequent reads, if the hash matches, we can avoid parsing the file, and the steep performance cost that comes with it.

Running `strace` on `meltano --no-environment config tap-exchange-rates-api list` reveals that the top-level `meltano` process reads `meltano.yml` 53 times.

@aaronsteers I'll take this opportunity to mention that if Meltano ran as a daemon, this in-memory caching could also apply to other calls to `meltano`, such as those mentioned earlier today during office hours wherein `meltano` calls a plugin which in turn calls `meltano` repeatedly to parallelize work.

Alternatively we could use on-disk caching by pickling the parsed `meltano.yml` content.

**Comment by edgarrmondragon** [comment] 2022-08-17 21:22
> Running `strace` on `meltano --no-environment config tap-exchange-rates-api list` reveals that the top-level `meltano` process reads `meltano.yml` 53 times.

@WillDaSilva Yeah, that's too much for what should be a read operation 😬.

**Comment by WillDaSilva** [comment] 2022-08-17 22:02
Looks like `deep_merge` does not preserve YAML comments. Might be worth addressing as another issue.

**Comment by edgarrmondragon** [comment] 2022-08-18 01:11
> Looks like `deep_merge` does not preserve YAML comments. Might be worth addressing as another issue.

@WillDaSilva that's handled elsewhere by `_raw_contents_map`:

https://github.com/meltano/meltano/blob/3bf8d54b69b2758fb2f3fa7fd6bd0abde156ff3c/src/meltano/core/project_files.py#L80

AFAICT `deep_merge` doesn't need to preserve comments since the merged Meltano object wouldn't care about those. Wdyt?

**Closed** 2022-08-24 17:51 UTC
Labels: cli, performance, User Support, kind/Bug, valuestream/Meltano
