### ISSUE TITLE
Add folder of `meltano.yml` samples to validate against JSON Schema rules

### ISSUE THREAD

**Issue by aaronsteers** [meltano/meltano#6181] opened 2022-06-14 02:47 UTC
> Another thing we should consider, I think, is having some reference samples in a `tests/resources/meltano-yml/` folder which themselves are validated against the JSON Schema definition linked above using some pytest code which would fail CI if examples do not conform to the schema.
>
> cc @pandemicsyn, @tayloramurphy, @pnadolny13

_Originally posted by @aaronsteers in https://github.com/meltano/meltano/issues/6170#issuecomment-1154646911_

The way we'd use this, I think, is that any time we add a new major feature which effects what is stored in yaml, we'd _also_ add/update one or more sample files, and those sample files would be tested against the JSON Schema.

**Comment by tayloramurphy** [comment] 2022-06-23 16:52
@aaronsteers is this a duplicate of:

- https://github.com/meltano/meltano/issues/6218

@pandemicsyn ?

**Comment by pandemicsyn** [comment] 2022-06-23 19:30
@tayloramurphy not so much of a duplicate as just yet check that we'll want to do as part of the integration tests. I'll fold this into #6218 as a spec entry. (will try to propose a build and spec this afternoon or monday)

**Comment by pandemicsyn** [comment] 2022-06-29 00:10
@aaronsteers fyi covered by https://github.com/meltano/meltano/pull/6303 which adds workflow to validate all of the example meltano yaml's whenever the schema changes or the examples are updated.

**Closed** 2022-07-01 18:34 UTC
Labels: CI/CD, kind/Feature, kind::tech debt, valuestream/Meltano
