### ISSUE TITLE
Add 'jobs' to the meltano project json schema

### ISSUE THREAD

**Issue by JulesHuisman** [meltano/meltano#6170] opened 2022-06-12 20:46 UTC
The `jobs` key currently shows an error in `meltano.yaml`. This is because it is missing in the [schema definition](https://github.com/meltano/meltano/blob/main/schema/meltano.schema.json).

<img width="222" alt="image" src="https://user-images.githubusercontent.com/26525996/173252897-3f0c4827-785c-4d15-9ee8-c0b84ac491df.png">

**Comment by aaronsteers** [comment] 2022-06-12 21:53
@JulesHuisman - I ran into this over the weekend too. Thanks for logging!

**Comment by vicradon** [comment] 2022-06-12 21:58
@aaronsteers 
I'll love to take on this issue. Do you mind guiding me on how I can contribute?

**Comment by pnadolny13** [comment] 2022-06-12 22:15
@JulesHuisman @aaronsteers I also noticed this last week. A couple others I saw that might be worth fixing all in one go are: mappers and "commands" keys. I think for "commands" we allow a dict of args/executable or a plain old command string but the json schema is requiring the args/executable, which isn't correct.

**Comment by aaronsteers** [comment] 2022-06-14 02:42
Hi, @JulesHuisman . This inline validation, and also the help text and auto-complete features, are driven by our JSON schema definitions. 

Specifically this file: https://github.com/meltano/meltano/blob/main/schema/meltano.schema.json

**Comment by JulesHuisman** [comment] 2022-06-14 08:28
Hi @aaronsteers, I can create a PR for this. Unless you want to pick this up @vicradon?

**Comment by pnadolny13** [comment] 2022-06-14 13:51
>Yes, I think so. And possibly also the things that @pnadolny13 mentioned above.

@vicradon @JulesHuisman it would be awesome if you got all of them fixed up but its up to you whether you want to pull in those additions I mentioned. I also agree with @aaronsteers that it would we great to have a way to assert some examples to prove our schemas are working as expected, since theyre quite large.

**Comment by vicradon** [comment] 2022-06-14 14:07
Working on it now @pnadolny13 🙂

**Comment by JulesHuisman** [comment] 2022-06-14 18:35
> @JulesHuisman Sorry to ask, but which object should I add the 'jobs' key to? Is it under `properties > definitions > environment > properties > config > properties > plugins`? I took a screenshot to verify.

I think the jobs are at the root level, so on the same level as `plugins`, `base_settings` and `schedules`. But it might be better to ask someone from the meltano team, as they probably know the schema inside out. :)

**Comment by pnadolny13** [comment] 2022-06-15 18:30
@vicradon following up on our [our slack thread](https://meltano.slack.com/archives/C013Z450LCD/p1655311751483699). Again thanks for taking this on!

Here are some details on the 3 things you were looking to fix. I'd suggest using the docs but also testing what the CLI creates in your local meltano.yml, since the docs are sometimes outdated, to get as close as you can to the schema. Then @pandemicsyn (or someone else from engineering) can review your PR for accuracy because they actually built these features so they know them best.

1. [jobs](https://docs.meltano.com/reference/command-line-interface#job): These are at the top level so would be added  at [the top level](https://github.com/meltano/meltano/blob/e1347b5c69873737e9c04027bacf8a18f6f484d2/schema/meltano.schema.json#L8).
2. [mappers](https://docs.meltano.com/concepts/plugins#mappers): are their own plugin so they would go under the [`plugins` properties](https://github.com/meltano/meltano/blob/e1347b5c69873737e9c04027bacf8a18f6f484d2/schema/meltano.schema.json#L46). The convention right now for the plugins is to use a new definition using the plugin name i.e. [extractors](https://github.com/meltano/meltano/blob/e1347b5c69873737e9c04027bacf8a18f6f484d2/schema/meltano.schema.json#L311) which validates the plugins top level properties keys with `additionalProperties` set to false so we can warn when extra properties or incorrectly spelled properties are present. In addition to that using the `allOf` setting, we also validate against the shared [plugin_generic](https://github.com/meltano/meltano/blob/e1347b5c69873737e9c04027bacf8a18f6f484d2/schema/meltano.schema.json#L110) definition to validate the contents for those properties at a finer grain.
3. [commands](https://docs.meltano.com/reference/command-line-interface#commands): we're [already validating this property](https://github.com/meltano/meltano/blob/e1347b5c69873737e9c04027bacf8a18f6f484d2/schema/meltano.schema.json#L180) but theres a bug based on the fact that you can define commands like:

```yaml
commands:
    my_command: xyz

or

commands:
    my_command:
        args: xyz
        executable: foo
```


Does that makes sense?

**Comment by pandemicsyn** [comment] 2022-06-15 18:37
@vicradon totally fine if you want to tackle all these issues at once, but I think it would also be totally acceptable to break these up into a couple of PR's (like maybe just adding Jobs in a first PR) if you wanted to.

**Comment by tayloramurphy** [comment] 2022-06-23 16:59
@vicradon are you still aiming to pick up this issue?

**Comment by vicradon** [comment] 2022-06-23 22:13
Hi @tayloramurphy 
I'm still aiming to take it up. My apologies for the delay. I'll continue today.

**Comment by tayloramurphy** [comment] 2022-06-24 16:48
@vicradon no worries! Let us know if you need any assistance 👍

**Comment by vicradon** [comment] 2022-06-27 07:05
Hi @tayloramurphy 
I'm not sure how to build a local meltano project from the repo code...
I want to be able to reproduce the issue.

**Comment by pandemicsyn** [comment] 2022-06-27 15:58
@vicradon have a peek at the [Contributor Guide](https://docs.meltano.com/contribute/), particularly the prereq's section: https://docs.meltano.com/contribute/prerequisites 

That guide can help get you setup with a local dev setup and a locally built meltano. With that in place, you'll also be able to run validation on your schema entries by running a:

```
poetry run python src/meltano/core/utils/validate_json_schema.py
```

@pnadolny13 might have some other tips/tricks but a local dev setup +  validate_json_schema.py are the two pieces that'll help the most I think.

**Comment by vicradon** [comment] 2022-06-28 13:34
So @pandemicsyn 
I ran the validate_json_schema.py file and got a validation error: "dditional properties are not allowed ('requires' was unexpected)". I think the error is related to extra fields (require, variant) in the discovery.yml file

<img width="474" alt="linting errors in yaml file" src="https://user-images.githubusercontent.com/40396070/176191748-bc864594-ed51-4cb6-bdab-de4e5c15c502.png">


Below is the full error output

```bash
Traceback (most recent call last):
  File "src/meltano/core/utils/validate_json_schema.py", line 19, in <module>
    validate(instance=yaml_content, schema=schema_content)
  File "/home/gitpod/.cache/pypoetry/virtualenvs/meltano-jZURQ037-py3.8/lib/python3.8/site-packages/jsonschema/validators.py", line 1058, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('requires' was unexpected)

Failed validating 'additionalProperties' in schema['properties']['orchestrators']['items']['allOf'][1]:
    {'additionalProperties': False,
     'properties': {'commands': {},
                    'description': {},
                    'docs': {},
                    'executable': {},
                    'label': {},
                    'name': {},
                    'namespace': {},
                    'pip_url': {},
                    'repo': {},
                    'settings': {},
                    'settings_group_validation': {}}}

On instance['orchestrators'][0]:
    {'docs': 'https://docs.meltano.com/guide/orchestration',
     'name': 'airflow',
     'namespace': 'airflow',
     'pip_url': 'apache-airflow==2.1.2 --constraint '
                'https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-${MELTANO__PYTHON_VERSION}.txt',
     'repo': 'https://github.com/apache/airflow',
     'requires': {'files': [{'name': 'airflow', 'variant': 'meltano'}]},
     'settings': [{'env': 'AIRFLOW__CORE__DAGS_FOLDER',
                   'name': 'core.dags_folder',
                   'value': '$MELTANO_PROJECT_ROOT/orchestrate/dags'},
                  {'env': 'AIRFLOW__CORE__PLUGINS_FOLDER',
                   'name': 'core.plugins_folder',
                   'value': '$MELTANO_PROJECT_ROOT/orchestrate/plugins'},
                  {'env': 'AIRFLOW__CORE__SQL_ALCHEMY_CONN',
                   'name': 'core.sql_alchemy_conn',
                   'value': 'sqlite:///$MELTANO_PROJECT_ROOT/.meltano/orchestrators/airflow/airflow.db'},
                  {'env': 'AIRFLOW__CORE__LOAD_EXAMPLES',
                   'name': 'core.load_examples',
                   'value': False},
                  {'env': 'AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION',
                   'name': 'core.dags_are_paused_at_creation',
                   'value': False}]}
```

**Comment by pandemicsyn** [comment] 2022-06-29 00:41
@vicradon ah it looks like the schema for discovery.yml might have drifted as well and/or possibly the test needs to be updated. Apologies, on the brokenness here, we've got some CI updates in the works that should help prevent this from happening in the future. 

/cc @pnadolny13 have you messed with this since the hub reorg by chance?

**Comment by pandemicsyn** [comment] 2022-06-29 01:26
I realized getting jobs added would actually be a bit more difficult than usual, since it has some abnormally complex requirements around the `tasks` field. So, I went ahead and sent a long a PR to add `jobs` and update `schedules` to support jobs as well (https://github.com/meltano/meltano/pull/6309).  

@vicradon once again, apologies, that we sent you down this path with a bunch of unexpected issues 😬

**Comment by pandemicsyn** [comment] 2022-06-29 20:44
@pnadolny13 i don't think it's just feature drift related, quite a few of the top-level keys (transformers, orchestrators, etc) in the discovery jsonschema are also failing because of mismatch in required fields (i.e. getting passed a `variant` key or missing a `logo_url` key).

**Comment by tayloramurphy** [comment] 2022-07-05 14:19
Closing since it seems like it was sorted in https://github.com/meltano/meltano/pull/6309/files

**Closed by tayloramurphy** 2022-07-05 14:19 UTC
Labels: Accepting Pull Requests, kind/Bug, valuestream/Meltano
