### ISSUE TITLE
bug: Schedules JSON schema doesn't accept cron expressions

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#6495] opened 2022-07-27 18:50 UTC
### Meltano Version

NA

### Python Version

NA

### Bug scope

Other

### Operating System

Any

### Description

https://github.com/meltano/meltano/blob/3a6ff7e7e167f51b9a5570eeaee48faed032a9c0/schema/meltano.schema.json#L769-L774

**Comment by tayloramurphy** [comment] 2022-07-27 18:51
FYI @aaronsteers I've added to the next iteration

**Comment by WillDaSilva** [comment] 2022-07-30 04:31
The schema states that we accept a UNIX cron expression, but in practice we accept whatever Airflow accepts, and Airflow accepts whatever [`croniter`](https://github.com/kiorky/croniter) accepts. I think resolving this issue should consist of these changes:
- Update `src/meltano/core/schedule.py::Schedule::cron_interval` to normalize the provided cron interval using `croniter` instead of the custom approach we currently use.
- Update `src/meltano/core/schedule.py::Schedule` to raise an error if the provided `interval` expression is invalid according to `croniter.croniter.is_valid` if it is not `None`.
- Create a regex for what `croniter` accepts, and update `schema/meltano.schema.json` to use it for the `interval` pattern. This doesn't have to be perfect, but should err towards accepting more that `croniter`, rather than declaring valid cron expressions as invalid.
- Add a parameterized test with many additional (valid and invalid) cron expressions...
  - for schema validation (to ensure the pattern is accurate).
  - for `Schedule` instance creation (to ensure validation is working as intended).

**Closed** 2022-08-09 17:35 UTC
Labels: Accepting Pull Requests, kind/Bug, valuestream/Meltano
