### ISSUE TITLE
Debug and iteration UX for mappers

### ISSUE THREAD

**Issue by pnadolny13** [meltano/meltano#6428] opened 2022-07-15 13:53 UTC
I was recently using mapper utilities for the first time in [the Squared configs](https://github.com/meltano/squared/blob/main/data/extract/mappers.meltano.yml) as part of adding [tap-spreadsheets-anywhere](https://github.com/meltano/squared/blob/main/data/extract/extractors.meltano.yml#L3)  and had to do some debugging before I got it working like I wanted, thats totally expected. I needed to iterate to figure out what I can do with simpleeval and to get it working as I expect but the iteration process was pretty difficult.

Is there a recommended way of debugging mappers? Could we document it? What do we think about supporting mappers using `meltano invoke` in some way?

While I was doing this I couldnt find a good way to test my mapper configs without running it as part of a full pipeline `meltano run tap-csv my-mapper target-jsonl`. Usually I would back out to `invoke` to debug but it doesnt look like mappers are supported. I tried outputting the raw results of the tap then piping into the mapper with no luck `cat results.json | meltano invoke my-mapper > mapped.json`. Using `meltano run` is also challenging because sometimes the target manipulates the records so I dont trust whats coming out of it, maybe target-jsonl doesnt and we could just add some docs to suggest using it to validate.

Ultimately I ended up using `meltano run` and directly editing the installed python package code to raise more info about failures until I got it right, which is a bad idea and most users would probably give up before doing something like this.

cc @tayloramurphy @pandemicsyn (since you worked on mappers) any thoughts?

**Comment by tayloramurphy** [comment] 2022-07-15 17:16
Duplicate of https://github.com/meltano/meltano/issues/3232

**Closed by tayloramurphy** 2022-07-15 17:16 UTC
Labels: ux
