### ISSUE TITLE
feature: Avoid initializing the snowplow tracker when usage stats are disabled or emitters can't be initialized

### ISSUE THREAD

**Issue by jaceksan** [meltano/meltano#8256] opened 2023-11-07 09:39 UTC
### Feature scope

CLI (options, error messages, logging, etc.)

### Description

I need to share the same virtual env with Meltano and dbt, because I want to orchestrate them with Dagster.

Currently, the snowplow-tracker is required by both Meltano and dbt, but they require different incompatible versions.

Please, stop initializing the tracker if the usage stats are disabled.

**Comment by tayloramurphy** [comment] 2023-11-07 17:53
@edgarrmondragon I know you did work on this. As I understand it there's not much we can do here b/c even though no events are sent the package is still there. Would we have to ship a version of Meltano w/o snowplow as a dependency to achieve this?

**Comment by edgarrmondragon** [comment] 2023-11-08 00:49
> @edgarrmondragon I know you did work on this. As I understand it there's not much we can do here b/c even though no events are sent the package is still there. Would we have to ship a version of Meltano w/o snowplow as a dependency to achieve this?

I think we should probably catch any errors raised during the initialization of the tracker, log an event at the warning level, then continue to execute the application. The biggest change would be updating all the places where the tracker is called to fire an event to make it instead a no-op.

Related:

* https://github.com/meltano/meltano/issues/7895

**Comment by edgarrmondragon** [comment] 2023-11-08 19:52
> @edgarrmondragon To avoid updating every piece of code that calls/uses the tracker, we could stub its functionality within our tracker class if the underlying Snowplow tracker fails to initialize. The code that calls the tracker doesn't need to ensure it actually runs, so no functionality should be affected, save for the telemetry being disabled of course.

@WillDaSilva That makes sense! So we could

1. Catch any exceptions when initializing emitters here: https://github.com/meltano/meltano/blob/72530e9579032aa96867f219f13948e5991c86f2/src/meltano/core/tracking/tracker.py#L116-L128
2. Log a warning that the tracker will not be initialized

With this, `Tracker.can_track` will already make calls from the cli code no-ops.

cc @jaceksan

**Comment by dresslife-shbh** [comment] 2023-11-09 19:56
@edgarrmondragon can i work on this?

**Comment by edgarrmondragon** [comment] 2023-11-10 16:16
> @edgarrmondragon can i work on this?

Yes, go for it 🙂

**Comment by edgarrmondragon** [comment] 2023-11-24 20:23
Note that this will only fix _some_ of the issues of installing dbt-core in the  virtual environment as Meltano. For example:

```bash
$ virtualenv venv
$ source venv/bin/activate
(venv) $ pip install meltano dbt-core
(venv) $ meltano init --no-usage-stats --force .
...
ImportError: cannot import name 'SelfDescribing' from 'snowplow_tracker'
```

The core issue is that both `snowplow-tracker` (required by meltano) and `minimal-snowplow-tracker` (required by dbt-core) install to the same path, i.e. `site-packages/snowplow_tracker`.

**Comment by jaceksan** [comment] 2023-11-30 12:11
I try to develop a solution based on your notes.
I may take some time, I am very busy with my official duties, you know ;-)

**Comment by nauxliu** [comment] 2023-12-31 12:00
I'm running into the same problem when trying to orchestrate dbt and meltano with Dagster. 
Any updates on this? Or is there a workaround?

**Comment by edgarrmondragon** [comment] 2024-01-08 23:54
> I'm running into the same problem when trying to orchestrate dbt and meltano with Dagster. Any updates on this? Or is there a workaround?

@nauxliu I'm not familiar with dagster to know how you'd execute Meltano or dbt from within, but the recommendation at the moment is to ensure Meltano and dbt are installed each in its own separate virtual environment if possible.

**Comment by edgarrmondragon** [comment] 2024-04-18 18:36
FYI starting with [dbt 1.8.0b3](https://github.com/dbt-labs/dbt-core/blob/main/CHANGELOG.md#dbt-core-180-b3---april-18-2024), it should be possible to run Meltano and dbt side by side in the same virtualenv, provided that Meltano is installed **after** dbt:

```
$ uv venv .venv --python python3.11
$ source .venv/bin/activate
$ (dbt-meltano) uv pip install 'dbt-core>=1.8.0b3'
$ (dbt-meltano) uv pip install meltano
$ (dbt-meltano) python -c 'from dbt.tracking import tracker'
```

**Comment by seunggs** [comment] 2024-05-08 21:29
This doesn't fix the issue for me - I installed dbt first and then meltano. Still getting:
```
TypeError: Emitter.__init__() got an unexpected keyword argument 'buffer_size'
```

I can confirm that everything works fine when I install everything else except for meltano.

**Comment by edgarrmondragon** [comment] 2024-05-17 02:12
> FYI starting with [dbt 1.8.0b3](https://github.com/dbt-labs/dbt-core/blob/main/CHANGELOG.md#dbt-core-180-b3---april-18-2024), it should be possible to run Meltano and dbt side by side in the same virtualenv, provided that Meltano is installed **after** dbt:
> 
> ```
> $ uv venv .venv --python python3.11
> $ source .venv/bin/activate
> $ (dbt-meltano) uv pip install 'dbt-core>=1.8.0b3'
> $ (dbt-meltano) uv pip install meltano
> $ (dbt-meltano) python -c 'from dbt.tracking import tracker'
> ```

With this in mind, I'll close this issue. Feel free to comment if you're still encountering issues with the Snowplow tracker when dbt and Meltano are installed together.

**Comment by dluo-sig** [comment] 2024-06-20 21:14
So it seems like there's no way to enforce the installation order of packages aside from manually creating a script.  This might also throw off people that use meltano and dbt in the same venv in the future as well.  Specifically, I am also using it through dagster.  Is this still an issue on dbt side because they use a fork of snowplow?  I followed all the other issues and came back full circle to this one.  It doesn't look like the suggestion to implement this feature has actually gone through.  Should the issue be reopened?

**Comment by edgarrmondragon** [comment] 2024-06-21 10:35
> So it seems like there's no way to enforce the installation order of packages aside from manually creating a script. This might also throw off people that use meltano and dbt in the same venv in the future as well.

I don't if this is still how pip works under the hood, but https://github.com/pypa/pip/issues/11572#issuecomment-1303601066 seems to suggest that having a requirements file like

```
dbt-core
meltano
snowplow-tracker
```

might alleviate the potentially nondeterministic installation order.

> Is this still an issue on dbt side because they use a fork of snowplow?

That's correct and AFAIK the dbt team is still undecided between options 1 and 2 in https://github.com/dbt-labs/dbt-core/issues/8719#issuecomment-1735945399 as the long-term fix.

> It doesn't look like the suggestion to implement this feature has actually gone through. Should the issue be reopened?

We can reopen it, but I don't think we will internally prioritize this. Also https://github.com/meltano/meltano/pull/8302 was too complex (imo!) for a patch, in great part due to the re-implementation of `SelfDescribingJson`. If we go that route, it'd be better to vendor the entire snowplow-tracker package, so maybe that's a potential solution if someone is interested in contributing.

**Comment by edgarrmondragon** [comment] 2024-06-24 12:31
I've opened https://github.com/meltano/meltano/issues/8597 to track the above proposal to vendor the snowplow tracker library in Meltano.

**Comment by edgarrmondragon** [comment] 2024-08-07 20:29
The next release of dbt-core (1.9?) will use `snowplow-tracker` instead of their old fork, so the incompatibility with Meltano should disappear:

- https://github.com/dbt-labs/dbt-core/issues/8409
- https://github.com/dbt-labs/dbt-core/pull/10530

I'm closing this and we still have https://github.com/meltano/meltano/issues/8597 to track and offer a solution if similar cases ever arise.

**Closed** 2024-08-07 20:29 UTC
Labels: Accepting Pull Requests, kind/Feature, valuestream/Meltano
